sudo: required
language: nodejs
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_1fdd192d7838_key -iv $encrypted_1fdd192d7838_iv
  -in kubernetes-deploy-test-1906-1a5534c038f7.json.enc -out kubernetes-deploy-test-1906-1a5534c038f7.json
  -d
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file
